[package]
name = "solari-transfers"
version = "0.1.0"
edition = "2024"

[dependencies]
valhalla-graphtile = { git = "https://github.com/stadiamaps/valinor", rev = "8e34e84", features = ["serde"] }
bit-set = "0.8.0"
anyhow = "1.0"
rstar = { version = "0.12", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
solari-geomath = { path = "../solari-geomath" }
geo-types = "0.7"
geo = "0.29"
